imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    secret: %secret%
    router:
        resource: %kernel.root_dir%/config/routing.yml
    templating:
        engines: ['twig']
    default_locale: "%locale%"
    form:
        csrf_protection:
            enabled: false
#           field_name: secretfield
    session:
        handler_id: ~
    translator: { fallback: "%locale%" }

twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
doctrine:
    dbal:
        driver: "%database_driver%"
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        charset: UTF8

doctrine_phpcr:
    # configure the PHPCR session
    session:
        backend: %phpcr_backend%
        workspace: "%phpcr_workspace%"
        username: "%phpcr_user%"
        password: "%phpcr_pass%"
    # enable the ODM layer
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: "%kernel.debug%"

    # http://symfony.com/doc/current/cmf/cookbook/database/create_new_project_phpcr_odm.html
    # http://symfony.com/doc/current/cmf/tutorial/introduction.html

cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        persistence:
            phpcr:
                route_basepath: /cms/routes
                use_sonata_admin: false
        controllers_by_class:
            Ddpkts\TestCmsBundle\Document\Page: Ddpkts\TestCmsBundle\Controller\DefaultController::pageAction
            Ddpkts\TestCmsBundle\Document\Post: Ddpkts\TestCmsBundle\Controller\DefaultController::pageAction

cmf_routing_auto:
    persistence:
        phpcr:
            enabled: true

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata_admin_doctrine_phpcr.tree_block:
            settings:
                id: '/cms'
            contexts: [admin]

sonata_admin:
    dashboard:
        blocks:
            - { position: left, type: sonata_admin_doctrine_phpcr.tree_block }
            - { position: right, type: sonata.admin.block.admin_list }

sonata_doctrine_phpcr_admin:
    document_tree_defaults: [locale]
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all
        Ddpkts\TestCmsBundle\Document\Page:
            valid_children:
                - Ddpkts\TestCmsBundle\Document\Post
        Ddpkts\TestCmsBundle\Document\Post:
            valid_children: []
        Ddpkts\TestCmsBundle\Document\Site:
            valid_children:
                - all

knp_menu:
    twig: true